version: '3.4'

services:
  latex:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    environment:
      API_KEY: ''

networks:
  default:
    external:
      name: network_main_net
